# Generated by Django 3.0.5 on 2020-07-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerbar', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
