# Generated by Django 3.0.5 on 2020-07-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerbar', '0004_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='whisky',
            name='image',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to=''),
        ),
    ]
