# Generated by Django 3.0.5 on 2020-07-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerbar', '0005_auto_20200707_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='rum',
            name='image',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to=''),
        ),
    ]
