# Generated by Django 3.0.5 on 2020-07-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerbar', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='category',
            field=models.CharField(default='beer', max_length=50),
        ),
        migrations.AddField(
            model_name='gin',
            name='category',
            field=models.CharField(default='wine', max_length=50),
        ),
        migrations.AddField(
            model_name='mezcal',
            name='category',
            field=models.CharField(default='mezcal', max_length=50),
        ),
        migrations.AddField(
            model_name='rum',
            name='category',
            field=models.CharField(default='rum', max_length=50),
        ),
        migrations.AddField(
            model_name='vodka',
            name='category',
            field=models.CharField(default='vodka', max_length=50),
        ),
        migrations.AddField(
            model_name='whisky',
            name='category',
            field=models.CharField(default='whisky', max_length=50),
        ),
        migrations.AddField(
            model_name='wine',
            name='category',
            field=models.CharField(default='wine', max_length=50),
        ),
    ]
