# Generated by Django 3.0.5 on 2020-07-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerbar', '0011_auto_20200723_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
