# Generated by Django 3.0.5 on 2020-07-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerbar', '0012_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default='admin', max_length=70),
        ),
    ]
